# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16ba74878f7ecfd63c016fa8da45ee6fcda21c6c07cdefe941d07e524f082ea7a49d20fdff7532a0c0a945e30a99fa58873cda9ebfe0f2cf0e603fd4c758f8d

test:
  secret_key_base: 81fcb75c718ed988f39d799358008f48e2e5cace7f279dea4bfd95488b987de8461884ab6c546e82a14c4b4cd01694c9c207f5d0de94dc31c09ac59f4f531a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
